sudo: false
language: node_js
node_js:
  - "10"
  - "12"

addons:
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost

before_install:
  - npm install -g npm@latest

script:
  - npm run standard
  - npm run validate
  - npm run nyc
